vault_section = "preprod"
idam_api_url = "https://idam-api.demo.platform.hmcts.net"
fees_api_url = "http://fees-register-api-demo.service.core-compute-demo.internal"
prd_api_old_url = "http://rpa-rd-professional-demo.service.core-compute-demo.internal"
prd_api_url = "http://rd-professional-api-aat.service.core-compute-aat.internal"
payment_api_url = "http://payment-api-demo.service.core-compute-demo.internal"
