vault_section = "test"
idam_api_url = "http://betaDevBccidamAppLB.reform.hmcts.net"
fees_api_url = "http://fees-register-api-saat.service.core-compute-saat.internal"
prd_api_old_url = "http://rpa-rd-professional-saat.service.core-compute-saat.internal"
prd_api_url = "http://rd-professional-api-saat.service.core-compute-saat.internal"
payment_api_url = "http://payment-api-saat.service.core-compute-saat.internal"