vault_section = "test"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
fees_api_url = "http://fees-register-api-saat.service.core-compute-saat.internal"
prd_api_url = "http://rpa-rd-professional-saat.service.core-compute-saat.internal"
payment_api_url = "http://payment-api-saat.service.core-compute-saat.internal"